# Generated by Django 5.2.5 on 2025-08-16 16:04

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cadastros', '0003_client'),
        ('servicos', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='serviceorder',
            name='customer_name',
        ),
        migrations.RemoveField(
            model_name='serviceorder',
            name='customer_phone',
        ),
        migrations.AddField(
            model_name='serviceorder',
            name='client',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='orders', to='cadastros.client'),
        ),
    ]
