# Generated by Django 5.2.5 on 2025-08-16 12:52

import django.db.models.deletion
import django.utils.timezone
import uuid
from decimal import Decimal
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cadastros', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Staff',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now, editable=False)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('full_name', models.CharField(blank=True, max_length=150)),
                ('phone', models.CharField(blank=True, max_length=32)),
                ('document', models.CharField(blank=True, max_length=20)),
                ('birth_date', models.DateField(blank=True, null=True)),
                ('address', models.CharField(blank=True, max_length=255)),
                ('hire_date', models.DateField(blank=True, null=True)),
                ('commission_percent', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=5)),
                ('is_active', models.BooleanField(default=True)),
                ('notes', models.TextField(blank=True)),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='%(class)ss', to=settings.AUTH_USER_MODEL)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='staff_profiles', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.AlterUniqueTogether(
            name='staffmembership',
            unique_together=set(),
        ),
        migrations.AddField(
            model_name='staffmembership',
            name='staff',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='memberships', to='cadastros.staff'),
            preserve_default=False,
        ),
        migrations.AlterUniqueTogether(
            name='staffmembership',
            unique_together={('staff', 'shop')},
        ),
        migrations.AddIndex(
            model_name='staff',
            index=models.Index(fields=['owner', 'is_active'], name='cadastros_s_owner_i_5306c5_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='staff',
            unique_together={('owner', 'user')},
        ),
        migrations.RemoveField(
            model_name='staffmembership',
            name='user',
        ),
    ]
